In [1]:
import picsure

In [2]:
token_file = "token.txt"

with open(token_file, "r") as f:
    my_token = f.read()

In [3]:
authorized_session = picsure.connect(
    picsure.Platform.BDC_AUTHORIZED,
    my_token
)

You're successfully connected to BDC Authorized as user george_colon@era.nih.gov!
Your token expires on 2026-06-13T14:40:16Z.

In [4]:
authorized_session.searchDictionary("age")

,conceptPath,name,display,description,dataType,studyId,values,min,max,allowFiltering,meta,studyAcronym
0,\phs000179\pht002239\phv00169388\Duration_Smok...,phv00169388,Duration_Smoking,Duration of smoking yrs,Continuous,phs000179,[],0.0,78.5,True,None,COPDGENE
1,\phs002907\AGE_C4R_BASELINE_BDC\,AGE_C4R_BASELINE_BDC,"Age at C4R baseline (Marchh 01, 2020)","Age at C4R baseline (Marchh 01, 2020)",Continuous,phs002907,[],38.0,90.0,True,None,C4R_JHS
2,\phs000200\pht001000\phv00078662\AGEFBIR\,phv00078662,AGEFBIR,Age at First Birth,Categorical,phs000200,"[20-29, 30+, < 20, Never had term pregnancy]",NaN,NaN,True,None,WHI
3,\phs000007\pht000395\phv00056587\age_s1\,phv00056587,age_s1,Age = StdyDtqa - DOB,Continuous,phs000007,[],29.0,86.0,True,None,FHS
4,\phs000007\pht000397\phv00056723\age_s2\,phv00056723,age_s2,Age (age = formdate - DOB),Continuous,phs000007,[],44.0,86.0,True,None,FHS
...,...,...,...,...,...,...,...,...,...,...,...,...
4483,\phs000007\pht000676\phv00066827\system1\,phv00066827,system1,Description/Label for anatomical main group - ...,Categorical,phs000007,"[ALIMENTARY TRACT AND METABOLISM, ANTIINFECTIV...",NaN,NaN,False,None,FHS
4484,\phs000007\pht000676\phv00066823\phrm_gp2\,phv00066823,phrm_gp2,Description/Label for pharmacological subgroup...,Categorical,phs000007,"[ACE INHIBITORS, PLAIN, ANTACIDS, ANTIGLAUCOMA...",NaN,NaN,False,None,FHS
4485,\phs000007\pht000676\phv00066833\MEDNAME\,phv00066833,MEDNAME,Medication name,Categorical,phs000007,"[(ANTIOXIDANT), (ETHIN. ESTRADIO, (ETHINYL EST...",NaN,NaN,False,None,FHS
4486,\phs000007\pht005141\phv00254644\fv057\,phv00254644,fv057,Medical History - Respiratory Symptoms: Do you...,Categorical,phs000007,"[No, Yes]",NaN,NaN,False,None,FHS
4487,\phs000179\pht002239\phv00569411\ptoa_surgothe...,phv00569411,ptoa_surgother_specify,Knee surgery: Other - specify,Categorical,phs000179,[1989--tibial plataeu 2001--unknown knee surg...,NaN,NaN,False,None,COPDGENE

In [5]:
authorized_session.showAllFacets()

,category,Category Display,display,description,value,count
0,dataset_id,Dataset,RECOVER_Adult (phs003463),Researching COVID to Enhance Recovery (RECOVER...,phs003463,160676
1,dataset_id,Dataset,FHS (phs000007),Framingham Cohort,phs000007,54985
2,dataset_id,Dataset,ARIC (phs000280),Atherosclerosis Risk in Communities (ARIC) Cohort,phs000280,26106
3,dataset_id,Dataset,RECOVER_Pediatric (phs003461),Researching COVID to Enhance Recovery (RECOVER...,phs003461,20680
4,dataset_id,Dataset,MESA (phs000209),Multi-Ethnic Study of Atherosclerosis (MESA) S...,phs000209,20086
...,...,...,...,...,...,...
494,data_source,Data Type,Genomic,Associated with genomic data,data_source_genomic,17
495,data_source,Data Type,Biosamples,Associated with biosample data,data_source_biosamples,8
496,data_source,Data Type,Electrocardiogram,Associated with electrocardiogram data,data_source_electrocardiogram,0
497,data_type,Type of Variable,Categorical,,categorical,208157
498,data_type,Type of Variable,Continuous,,continuous,115781

In [6]:
child_facet = authorized_session.facets()
child_facet.add("Consortium_Curated_Facets", '06m-post index')
child_facet.view()

authorized_session.searchDictionary("", facets=child_facet)

,conceptPath,name,display,description,dataType,studyId,values,min,max,allowFiltering,meta,studyAcronym
0,\phs003463\RECOVER_Adult\biospecimens\ac_colld...,rc-ra1:ac_colldt|inf|v6,Date of Biospecimens form collection: [Infecte...,Answerdata Form: biospecimens Field: ac_colldt...,Categorical,phs003463,"[2021-01-03, 2021-03-05, 2021-03-18, 2021-03-2...",NaN,NaN,True,None,RECOVER_Adult
1,\phs003463\RECOVER_Adult\biospecimens\ac_colld...,rc-ra1:ac_colldt|noninf|v6,Date of Biospecimens form collection: [Non-inf...,Answerdata Form: biospecimens Field: ac_colldt...,Categorical,phs003463,"[2021-03-19, 2021-06-18, 2022-01-01, 2022-01-0...",NaN,NaN,True,None,RECOVER_Adult
2,\phs003463\RECOVER_Adult\biospecimens\ac_sampl...,rc-ra1:ac_sample_kit_type|inf|v6,Select Kit type: [Infected-06m post-index],Answerdata Form: biospecimens Field: ac_sample...,Categorical,phs003463,[ExamOne RECOVER Adult Tier 1 Mayo Kit 1 - Bas...,NaN,NaN,True,None,RECOVER_Adult
3,\phs003463\RECOVER_Adult\biospecimens\ac_kit_d...,rc-ra1:ac_kit_date_time|noninf|v6,Date and Time of Collection [Non-infected-06m ...,Answerdata Form: biospecimens Field: ac_kit_da...,Categorical,phs003463,"[2021-03-19, 2021-06-18, 2022-01-01, 2022-01-0...",NaN,NaN,True,None,RECOVER_Adult
4,\phs003463\RECOVER_Adult\biospecimens\ac_kit_d...,rc-ra1:ac_kit_date_time|inf|v6,Date and Time of Collection [Infected-06m post...,Answerdata Form: biospecimens Field: ac_kit_da...,Categorical,phs003463,"[2021-01-03, 2021-03-05, 2021-03-18, 2021-03-2...",NaN,NaN,True,None,RECOVER_Adult
...,...,...,...,...,...,...,...,...,...,...,...,...
7955,\phs003463\RECOVER_Adult\surveys\pregnancy\pre...,rc-ra1:preg_coviddefectspec_1|inf|v6,What type of birth defect did your baby have? ...,Answerdata Form: pregnancy Field: preg_covidde...,Categorical,phs003463,[Limbs (extremities)],NaN,NaN,False,None,RECOVER_Adult
7956,\phs003463\RECOVER_Adult\surveys\pregnancy\pre...,rc-ra1:preg_covidwtlb_1|inf|v6,Pounds (Weight at birth): [Infected-06m post-i...,Answerdata Form: pregnancy Field: preg_covidwt...,Continuous,phs003463,[],2.0,9.0,False,None,RECOVER_Adult
7957,\phs003463\RECOVER_Adult\surveys\pregnancy\pre...,rc-ra1:preg_covidwtlb_1|noninf|v6,Pounds (Weight at birth): [Non-infected-06m po...,Answerdata Form: pregnancy Field: preg_covidwt...,Continuous,phs003463,[],3.0,9.0,False,None,RECOVER_Adult
7958,\phs003463\RECOVER_Adult\surveys\pregnancy\pre...,rc-ra1:preg_covidnicu_1|inf|v6,Was your baby admitted to the neonatal intensi...,Answerdata Form: pregnancy Field: preg_covidni...,Categorical,phs003463,"[No, Yes]",NaN,NaN,False,None,RECOVER_Adult
7959,\phs003463\RECOVER_Adult\surveys\pregnancy\pre...,rc-ra1:preg_covidnicu_1|noninf|v6,Was your baby admitted to the neonatal intensi...,Answerdata Form: pregnancy Field: preg_covidni...,Categorical,phs003463,"[No, Yes]",NaN,NaN,False,None,RECOVER_Adult

In [7]:
facets = authorized_session.facets()
facets.add("dataset_id", "phs000007")
facets.view()

{'dataset_id': ['phs000007'],
 'Consortium_Curated_Facets': [],
 'common_data_elements': [],
 'data_source': [],
 'data_type': []}

In [8]:
authorized_session.searchDictionary("sex", facets=facets)

,conceptPath,name,display,description,dataType,studyId,values,min,max,allowFiltering,meta,studyAcronym
0,\phs000007\pht004374\phv00253990\sex\,phv00253990,sex,Sex of the participant,Categorical,phs000007,"[Female, Male]",NaN,NaN,True,None,FHS
1,\phs000007\pht007777\phv00369653\SEX\,phv00369653,SEX,Sex of participant,Categorical,phs000007,"[Female, Male]",NaN,NaN,True,None,FHS
2,\phs000007\pht016160\phv00568089\sex\,phv00568089,sex,Sex of the participant,Categorical,phs000007,"[Female, Male]",NaN,NaN,True,None,FHS
3,\phs000007\pht015172\phv00549391\sex\,phv00549391,sex,Sex of the participant,Categorical,phs000007,"[Female, Male]",NaN,NaN,True,None,FHS
4,\phs000007\pht016158\phv00567242\sex\,phv00567242,sex,Sex of the participant,Categorical,phs000007,"[Female, Male]",NaN,NaN,True,None,FHS
...,...,...,...,...,...,...,...,...,...,...,...,...
75,\phs000007\pht000676\phv00066829\phrm_gp1\,phv00066829,phrm_gp1,Description/Label for pharmacological subgroup...,Categorical,phs000007,"[ACE INHIBITORS, PLAIN, ADRENERGICS FOR SYSTEM...",NaN,NaN,False,None,FHS
76,\phs000007\pht000676\phv00066827\system1\,phv00066827,system1,Description/Label for anatomical main group - ...,Categorical,phs000007,"[ALIMENTARY TRACT AND METABOLISM, ANTIINFECTIV...",NaN,NaN,False,None,FHS
77,\phs000007\pht000676\phv00066845\system4\,phv00066845,system4,Description/Label for anatomical main group - ...,Categorical,phs000007,"[GENITO URINARY SYSTEM AND SEX HORMONES, RESPI...",NaN,NaN,False,None,FHS
78,\phs000007\pht000676\phv00066821\system2\,phv00066821,system2,Description/Label for anatomical main group - ...,Categorical,phs000007,"[ALIMENTARY TRACT AND METABOLISM, BLOOD AND BL...",NaN,NaN,False,None,FHS
79,\phs000007\pht000676\phv00066841\ther_gp3\,phv00066841,ther_gp3,Description/Label for therapeutic subgroup - t...,Categorical,phs000007,"[ANALGESICS, ANTIEPILEPTICS, ANTIHEMORRHAGICS,...",NaN,NaN,False,None,FHS