In [1]:
import picsure

In [2]:
token_file = "token.txt"

with open(token_file, "r") as f:
    my_token = f.read()

In [3]:
authorized_session = picsure.connect(
    picsure.Platform.BDC_AUTHORIZED,
    my_token,
    dev_mode=True
)

picsure.http /psama/user/me 200 230ms in=0B out=4.1KB retry=0
picsure.http /picsure/info/resources 200 133ms in=0B out=213B retry=0
picsure.http /psama/user/me/queryTemplate/ 200 101ms in=0B out=1.8KB retry=0
picsure.http /picsure/proxy/dictionary-api/concepts?page_number=0&page_size=1 200 126ms in=840B out=1.2KB retry=0
picsure.connect connect 0ms

You're successfully connected to BDC Authorized as user george_colon@era.nih.gov!
Your token expires on 2026-06-13T14:40:16Z.

In [4]:
all_facets = authorized_session.showAllFacets()
all_facets

picsure.http /picsure/proxy/dictionary-api/facets 200 130ms in=840B out=113.4KB retry=0
picsure.fn session.showAllFacets 135ms

,category,Category Display,display,description,value,count
0,dataset_id,Dataset,RECOVER_Adult (phs003463),Researching COVID to Enhance Recovery (RECOVER...,phs003463,160676
1,dataset_id,Dataset,FHS (phs000007),Framingham Cohort,phs000007,54985
2,dataset_id,Dataset,ARIC (phs000280),Atherosclerosis Risk in Communities (ARIC) Cohort,phs000280,26106
3,dataset_id,Dataset,RECOVER_Pediatric (phs003461),Researching COVID to Enhance Recovery (RECOVER...,phs003461,20680
4,dataset_id,Dataset,MESA (phs000209),Multi-Ethnic Study of Atherosclerosis (MESA) S...,phs000209,20086
...,...,...,...,...,...,...
494,data_source,Data Type,Genomic,Associated with genomic data,data_source_genomic,17
495,data_source,Data Type,Biosamples,Associated with biosample data,data_source_biosamples,8
496,data_source,Data Type,Electrocardiogram,Associated with electrocardiogram data,data_source_electrocardiogram,0
497,data_type,Type of Variable,Categorical,,categorical,208157
498,data_type,Type of Variable,Continuous,,continuous,115781

In [5]:
tutorial_biolincc_framingham_facet = authorized_session.facets()
tutorial_biolincc_framingham_facet.add('dataset_id', 'tutorial-biolincc_framingham')

picsure.http /picsure/proxy/dictionary-api/facets 200 128ms in=840B out=113.4KB retry=0
picsure.fn session.facets 130ms

In [6]:
tutorial_search_results = authorized_session.searchDictionary("Current cigarette smoking at exam", facets=tutorial_biolincc_framingham_facet)
tutorial_search_results['values']

picsure.http /picsure/proxy/dictionary-api/concepts?page_number=0&page_size=323952 200 122ms in=1.2KB out=697B retry=0
picsure.fn session.searchDictionary 123ms

0    [Current smoker, Not current smoker]
Name: values, dtype: object

In [7]:
cursmoke_var = tutorial_search_results[tutorial_search_results['name'] == 'CURSMOKE']
cursmoke_var

,conceptPath,name,display,description,dataType,studyId,values,min,max,allowFiltering,meta,studyAcronym
0,\tutorial-biolincc_framingham\CURSMOKE\,CURSMOKE,CURSMOKE,Current cigarette smoking at exam,Categorical,tutorial-biolincc_framingham,"[Current smoker, Not current smoker]",None,None,True,None,biolincc_framingham

In [8]:
raw_values = cursmoke_var['values'].iloc[0]
raw_values

['Current smoker', 'Not current smoker']

In [9]:
cursmoke = picsure.createSubQuery(
    cursmoke_var['conceptPath'].iloc[0],
    type=picsure.ClauseType.FILTER,
    categories=cursmoke_var['values'].iloc[0]
)

In [10]:
query = authorized_session.runQuery(cursmoke, type=picsure.QueryType.COUNT)

picsure.http /picsure/v3/query/sync 200 292ms in=326B out=4B retry=0
picsure.fn session.runQuery 295ms

In [11]:
query.value

4434

In [12]:
authorized_session.dev_events()

,timestamp,kind,name,duration_ms,bytes_in,bytes_out,status,retry,error,metadata
0,2026-05-14 14:51:44.230167+00:00,http,/psama/user/me,229.803333,0.0,4180.0,200.0,0,None,{}
1,2026-05-14 14:51:44.363975+00:00,http,/picsure/info/resources,133.102333,0.0,213.0,200.0,0,None,{}
2,2026-05-14 14:51:44.465509+00:00,http,/psama/user/me/queryTemplate/,100.790875,0.0,1862.0,200.0,0,None,{}
3,2026-05-14 14:51:44.592347+00:00,http,/picsure/proxy/dictionary-api/concepts?page_nu...,126.269375,840.0,1195.0,200.0,0,None,{}
4,2026-05-14 14:51:44.593173+00:00,connect,connect,0.000000,NaN,NaN,NaN,0,None,"{'resources': 4, 'consents': 50, 'total_concep..."
5,2026-05-14 14:51:44.784444+00:00,http,/picsure/proxy/dictionary-api/facets,130.080667,840.0,116115.0,200.0,0,None,{}
6,2026-05-14 14:51:44.789271+00:00,function,session.showAllFacets,134.942875,NaN,NaN,NaN,0,None,"{'df_rows': 499, 'df_cols': 6}"
7,2026-05-14 14:51:44.983407+00:00,http,/picsure/proxy/dictionary-api/facets,128.230625,840.0,116115.0,200.0,0,None,{}
8,2026-05-14 14:51:44.985074+00:00,function,session.facets,129.926125,NaN,NaN,NaN,0,None,{}
9,2026-05-14 14:51:45.173203+00:00,http,/picsure/proxy/dictionary-api/concepts?page_nu...,121.754375,1222.0,697.0,200.0,0,None,{}
10,2026-05-14 14:51:45.174093+00:00,function,session.searchDictionary,122.762084,NaN,NaN,NaN,0,None,"{'df_rows': 1, 'df_cols': 12}"
11,2026-05-14 14:51:45.962845+00:00,http,/picsure/v3/query/sync,292.291542,326.0,4.0,200.0,0,None,{}
12,2026-05-14 14:51:45.963305+00:00,function,session.runQuery,294.917500,NaN,NaN,NaN,0,None,{}